### ISSUE TITLE
Convert to typescript

### ISSUE THREAD

**Issue by Pike** [mozilla/react-content-marker#7]
In line with what we're doing the primary(?) consumer of this library, Pontoon, we should probably convert this to typescript, and export type definitions.

Got a WIP in the works.

CC @adngdb @mathjazz

**Comment by mathjazz** [comment]
Also CCing @jotes, who wanted to add additional functionality to the library.

**Comment by jotes** [comment]
@mathjazz Thanks for the ping. I can wait until the migration lands on the main branch.

**Comment by Pike** [comment]
This landed in #8
